# Generated by Django 5.0 on 2024-01-10 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Advisor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('id_number', models.CharField(max_length=150)),
                ('year', models.CharField(max_length=150)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Advisor.advisor')),
            ],
        ),
    ]
